# Generated by Django 6.0.3 on 2026-03-17 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('billing', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('strength', models.CharField(blank=True, default='', max_length=128)),
                ('form', models.CharField(blank=True, default='', max_length=64)),
                ('reorder_level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='pharmacy_me_name_46a660_idx'), models.Index(fields=['sku'], name='pharmacy_me_sku_cb5950_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='pharmacy.medication')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('ADJUST', 'Adjust'), ('DISPENSE', 'Dispense')], max_length=10)),
                ('quantity_delta', models.IntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_txns', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='txns', to='pharmacy.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to='appointments.appointment')),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispenses', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='patients.patient')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispenses', to='pharmacy.stocklot')),
            ],
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['medication', 'expiry_date'], name='pharmacy_st_medicat_495e65_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytxn',
            index=models.Index(fields=['txn_type', 'created_at'], name='pharmacy_in_txn_typ_fcdc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytxn',
            index=models.Index(fields=['performed_by', 'created_at'], name='pharmacy_in_perform_023d87_idx'),
        ),
        migrations.AddIndex(
            model_name='dispense',
            index=models.Index(fields=['patient', 'dispensed_at'], name='pharmacy_di_patient_8c4134_idx'),
        ),
    ]
