# Generated by Django 6.0.3 on 2026-03-17 19:25

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked in'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='SCHEDULED', max_length=20)),
                ('reason', core.fields.EncryptedTextField(blank=True, default='')),
                ('clinical_notes', core.fields.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['doctor', 'start_at'], name='appointment_doctor__f2389e_idx'), models.Index(fields=['patient', 'start_at'], name='appointment_patient_4b5ed5_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
            },
        ),
    ]
