# Generated by Django 6.0.3 on 2026-03-17 19:25

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('address', core.fields.EncryptedTextField(blank=True, default='')),
                ('emergency_contact', core.fields.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mrn'], name='patients_pa_mrn_d0102f_idx'), models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'), models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx')],
            },
        ),
    ]
